### ISSUE TITLE
[BUG] Cannot resize Global Minimum Needs Configuration Window

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1944]
# Problem
I cannot resize Global Minimum Needs Configuration's Window vertically. In the first time the window appear was really big that i need to resize it to find OK button that located in bottom window, but I only can resize the window horizontally and when i want to resize the window vertically, i can't resize it. Here's the screenshot for initial window appear:
![inasafe_1](https://cloud.githubusercontent.com/assets/2520159/7678539/244a950c-fd7f-11e4-934c-82ace5345439.png)

# Platform
I'm running InaSAFE 3.2.0.dev-master in QGIS 2.8.2 with Windows 7 64bit as OS

**Comment by lucernae** [comment]
This is a duplicate issue of #1926 I already included some commit but we haven't merge this.
Seeing this is a critical issue, I guess I will cherry pick the commit on separate PR.

**Comment by Jannes123** [comment]
Please check that you are working from latest repo I have also fixed this
problem twice now once for master and for develop

**Comment by lucernae** [comment]
Haha... yes, this is going crazy. But, this still occurs in develop branch. So, I assume my commit about this haven't been merged. I will make another PR and merge this ASAP, so we can move on :p

**Comment by Jannes123** [comment]
Hi Rizky, yes I think your changes were not mergeable because there were
some other design changes with the scrollbars.
